version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /var/lib/docker:/var/lib/docker
      - /var/run/systemd:/var/run/systemd
      - /etc/kubernetes:/etc/kubernetes
      - /var/lib/kubelet:/var/lib/kubelet
      - /var/lib/minikube:/var/lib/minikube
      - /var/lib/kubeadm.yaml:/var/lib/kubeadm.yaml
    privileged: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
